services:
  mongo:
    image: mongo
    container_name: healthcare-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: healthcare-chroma
    ports:
      - '8001:8000'
    volumes:
      - chroma_data:/chroma/.chroma
    restart: always

volumes:
  mongo-data:
  chroma_data:
